
default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("PGUSER") { 'postgres' } %>
  password: <%= ENV.fetch("PGPASSWORD") { "" } %>
  host: <%= ENV.fetch("PGHOST") { 'localhost' } %>
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: wishlist_dev

  
test:
  <<: *default
  database: wishlist_test


production:
  <<: *default
  database: wishlist_production
  username: ktplatform
  password: <%= ENV['KTPLATFORM_DATABASE_PASSWORD'] %>
